bf16: true
cutoff_len: 4096
dataset: mllm_demo
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: true
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 128
lora_dropout: 0.05
lora_rank: 64
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 2345
model_name_or_path: /data/wtt/wjx_code/VLM/Qwen2.5-VL-7B-Instruct/
num_train_epochs: 9.0
optim: adamw_torch
output_dir: saves/Qwen2.5-7B-Instruct/lora/Qwen2.5-VL-7B-Instruct-Epoch=9
packing: false
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
save_steps: 100
stage: sft
template: qwen2_vl
trust_remote_code: true
val_size: 0.01
warmup_steps: 0
